field.formatter.settings.FlickrStreamDefaultFormatter:
  type: mapping
  label: 'FlickrStreamDefaultFormatter images style'
  mapping:
    flickr_images_style:
      type: string
      label: 'Flickr image style'